project:
  type: website

website:
  title: "Katherine Brown"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles_blue.css
    toc: true

editor: source

