project:
  type: website
  output-dir: docs

website:
  title: "Katherine Brown"
  navbar:
    background: light
    logo: images/favicon.ico
    left:
      - href: index.qmd
        text: Home
      - href: reports_grid.qmd
        text: Reports
      - href: about.qmd
        text: About
      - href: certifications/certifications.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles_blue.css
    toc: true

editor: source

