project:
  type: website
  output-dir: _site

website:
  title: "Katherine Brown"
  navbar:
    background: light
    logo: images/favicon.ico
    left:
      - href: index.qmd
        text: Home
      - href: reports_grid.qmd
        text: Reports
      - href: certifications/certifications.qmd
        text: Certifications
    right: 
      - href: about.qmd
        text: Site
  repo-url: "https://github.com/j-jayes/kb"
  page-footer: '© 2022, Katherine Brown'

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    css: styles_blue.css
    toc: true

editor: source

